# Generated by Django 5.1.1 on 2024-09-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('imgfolderid', models.AutoField(primary_key=True, serialize=False)),
                ('pdfid', models.IntegerField()),
                ('imgfolderpath', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('payload', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
